server:
  port: 8761

spring:
  # Spring Boot Admin Client
  boot:
    admin:
      client:
        auto-registration: true
        url: http://spring-boot-admin:9090
        instance:
          service-url: http://localhost:8761
          name: Spring Cloud Eureka Server
        
# Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Eeureka Server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false