spring:
  application:
    name: spring-cloud-eureka-server
  boot:
    admin:
      client:
        auto-registration: true
        url: http://localhost:9090
        instance:
          service-url: http://localhost:8761
          name: Spring Cloud Eureka Server


server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false