spring:
  boot:
    admin:
      client:
        auto-registration: true
        url: ${SPRING_BOOT_ADMIN_URI:http://localhost:9090}
        instance:
          service-url: ${EUREKA_URI:http://localhost}:${server.port}
          name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true