spring:
  # Spring Boot Admin Client
  boot:
    admin:
      client:
        auto-registration: true
        url: http://spring-boot-admin:9090 
        instance:
          service-url: http://user-service:8080
          name: User Service
  
  datasource:
    url: jdbc:mariadb://mariadb:3306/twitter_clone
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialectd
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

# Eeureka Server
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://spring-eureka:8761/eureka/
